# to find and replace in vs code use "ctrl+h"

FROM ubuntu:latest

LABEL name="Yogesh"

# ARG variables are only available during the build process of the image, not persisted in final image 
# whereas ENV variables are available during build process and final image as well.
# ARG variables used to pass build-time variables

ARG terraform_version='1.6.6'\   
    packer_version='1.8.0'

RUN apt update && apt install -y jq net-tools curl wget unzip\
    && apt install -y nginx iputils-ping

RUN wget https://releases.hashicorp.com/terraform/${terraform_version}/terraform_${terraform_version}_linux_amd64.zip \
    && wget https://releases.hashicorp.com/packer/${packer_version}/packer_${packer_version}_linux_amd64.zip \
    && unzip terraform_${terraform_version}_linux_amd64.zip && unzip packer_${packer_version}_linux_amd64.zip\
    && chmod 777 terraform && chmod 777 packer\
    && ./terraform version && ./packer version

CMD [ "nginx","-g","daemon off;" ]

